id: IB73BF125
legacy_id: P009398
ocr_import_info:
  bdrc_scan_id: W8602
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T11:34:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:19:28.965996+00:00'
last_modified: 2022-09-04 11:19:49.276716
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8602
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8602
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སེ་ར་རྗེ་བཙུན་གྱིས་མཛད་པའི་ཚད་མ་རྣམ་འགྲེལ་གྱི་དོན་འགྲེལ་དང་མཐའ་དཔྱོད་སོགས།
  author: སེ་ར་རྗེ་བཙུན་ཆོས་ཀྱི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.661805872882931
  ocr_word_median_confidence_index: 0.699999988079071
quality: null
bases:
  I1KG12162:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12162
      total_pages: 614
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12162.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.661805872882931
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
