id: P009398
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8602
  title: སེ་ར་རྗེ་བཙུན་གྱིས་མཛད་པའི་ཚད་མ་རྣམ་འགྲེལ་གྱི་དོན་འགྲེལ་དང་མཐའ་དཔྱོད་སོགས།
  author: ''
  volumes:
    7055711b90b0404fa8c040fc3ff44981:
      image_group_id: I1KG12162
      title: ''
      volume_number: 1
      total_pages: 614
      base_file: v001.txt
